### ISSUE TITLE
Using context variables to store current bot instance

### ISSUE THREAD

**Issue by Bluenix2** [wumpyproject/wumpy#13]
## Summary

There are many cases where one might want to get access to the current bot (the bot that invoked this callback) to be able to access various attributes or their own methods.

This issue proposes the use of context variables and public functions that wrap them as a way to get the bot.

## Description

There are many work-arounds to get the bot without passing it around, for example Python Discord sets a module-level attribute to the created instance before loading all extensions and starting the bot while discord.py encourages using what they call cogs and storing the bot in an attribute upon loading of the cog.

This isn't perfect and the former has the downside of not being friendly towards running multiple bots. Even though multiple bots running at the same time won't be very widely used, I think it is important that the compatibility for it stays to ensure that the state that all classes the library has stays contained. The latter option doesn't work for Wumpy either as the cogs functionality hasn't been mirrored from discord.py

Therefore, none of any previously used options fully address the issue in a way that fits Wumpy.

Another issue I would like to bring up is how to be type-friendly even while the bot can be accessed. discord.py solves this with very complicated generics and type variables. Most things with a bot or context instance has been turned into a generic. Another approach to solving this, would be having utility functions that return the bot instance *but typed* as the type passed into it.

**Context variables like this solve both issues,** the rough code looks somewhat like this:
```python
T = TypeVar('T', bound=Bot)

_running_bot = ContextVar()


def get_bot(cls: Type[T] = Bot) -> T:
    return _running_bot.get()
```
As you can see, subclasses can be correctly annotated by being able to pass it into the function fixing that issue. This keeps the code-base clean without going down the same issue that discord.py did with generics.

## Tasks

- [ ] Create context variables for each core class (bot, requester, cache)
- [ ] Wrap their getters in a public-facing function
- [ ] Set the context variables during startup of the bot
  - [ ] Alternatively, set them right before executing the callback (further testing required)
