### ISSUE TITLE
Allow using different HTTP clients

### ISSUE THREAD

**Issue by Bluenix2** [wumpyproject/wumpy#22]
## Summary

In some cases, one may decide to use a different HTTP client than HTTPX. This is possible to implement by subclassing `Requester` but internal attributes will need to be handled with to get it to work.

The required base class `Requester` required for endpoints should be switched out to a pure typing-only variant.

Unfortunately, nothing can be done about the HTTPX dependency.

## Tasks

- [ ] Create an abstract `Requester` and rename the current one to `HTTPXRequester`
- [ ] Rename `GuildRequester` and similar endpoint classes to `GuildEndpoints` (which inherit from the new `Requester` for typing purposes)
- [ ] Update `APIClient` to inherit the `HTTPXRequester` implementation

**Comment by Bluenix2** [comment]
This was implemented in f7202616170ecef406f9f9773bbeda58e553ca44 and 724f591628656b70f31149785d7dbd6661c7d392.
